export const GET_PRODUCT_INFO_INITIATED = "GET_PRODUCT_INFO_INITIATED";
export const GET_PRODUCT_INFO_SUCCESS = "GET_PRODUCT_INFO_SUCCESS";
export const GET_PRODUCT_INFO_FAIL = "GET_PRODUCT_INFO_FAIL";
export const GET_PRODUCT_INFO_COMPLETE = "GET_PRODUCT_INFO_COMPLETE";
